// ─── Chat Module ───
// تست شده - بدون ضرورت تغییر ندهید

            {/* CHAT */}
            {tab==="chat"&&(
              <>
                <div style={{padding:"8px 14px",borderBottom:`1px solid ${C.border}`,background:C.surface,display:"flex",alignItems:"center",gap:10,flexShrink:0}}>
                  {dm?<><Av user={USERS.find(u=>u.id===dm)} size={34}/><div><div style={{fontSize:13,fontWeight:600}}>{USERS.find(u=>u.id===dm)?.name}</div><button onClick={()=>{setShowMsgSearch(p=>!p);setMsgSearch("");}} style={{background:"none",border:"none",color:showMsgSearch?C.teal:C.textMuted,cursor:"pointer",padding:4,display:"flex",alignItems:"center",WebkitTapHighlightColor:"transparent"}}><svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg></button><div style={{fontSize:11,color:C.teal}}>{USERS.find(u=>u.id===dm)?.role}</div><button onClick={()=>{setShowMsgSearch(p=>!p);setMsgSearch("");}} style={{background:"none",border:"none",color:showMsgSearch?C.teal:C.textMuted,cursor:"pointer",padding:4,display:"flex",alignItems:"center",WebkitTapHighlightColor:"transparent"}}><svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg></button></div><button onClick={()=>{setShowMsgSearch(p=>!p);setMsgSearch("");}} style={{background:"none",border:"none",color:showMsgSearch?C.teal:C.textMuted,cursor:"pointer",padding:4,display:"flex",alignItems:"center",WebkitTapHighlightColor:"transparent"}}><svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg></button></>:<><div style={{width:34,height:34,borderRadius:"50%",background:C.surfaceAlt,display:"flex",alignItems:"center",justifyContent:"center",fontSize:14,fontWeight:700,color:C.textDim}}>#</div><button onClick={()=>{setShowMsgSearch(p=>!p);setMsgSearch("");}} style={{background:"none",border:"none",color:showMsgSearch?C.teal:C.textMuted,cursor:"pointer",padding:4,display:"flex",alignItems:"center",WebkitTapHighlightColor:"transparent"}}><svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg></button><span style={{fontSize:13,fontWeight:600}}>{CHANNELS.find(x=>x.id===channel)?.name}</span></>}
                </div>
                {showMsgSearch&&<div style={{padding:"6px 14px",background:C.surfaceAlt,flexShrink:0,borderBottom:`1px solid ${C.border}`}}>
                    <input style={{width:"100%",background:C.bg,border:`1px solid ${C.border}`,borderRadius:20,padding:"7px 14px",color:C.text,fontSize:14,outline:"none",direction:"rtl",boxSizing:"border-box",fontFamily:"inherit"}} placeholder="جستجو در پیام‌ها..." value={msgSearch} onChange={e=>setMsgSearch(e.target.value)} autoFocus/>
                  </div>}
                <div style={{flex:1,overflowY:"auto",padding:"12px 14px",display:"flex",flexDirection:"column",gap:2,WebkitOverflowScrolling:"touch",background:C.bg}}>
                  {curMsgs.filter(msg=>!msgSearch||msg.text?.includes(msgSearch)).map(msg=>{const u=USERS.find(x=>x.id===msg.userId);const mine=msg.userId===me.id;return(<div key={msg.id} style={{display:"flex",justifyContent:mine?"flex-start":"flex-end",marginBottom:4}}><div style={{maxWidth:"78%",background:mine?C.myBubble:C.theirBubble,borderRadius:mine?"4px 12px 12px 12px":"12px 4px 12px 12px",padding:"8px 12px 6px"}}>{!mine&&<div style={{fontSize:11,color:C.teal,fontWeight:700,marginBottom:3}}>{u?.lastName}</div>}<div style={{fontSize:14,lineHeight:1.6,color:C.text,wordBreak:"break-word"}}>{msg.text}</div><div style={{fontSize:10,color:C.textDim,marginTop:3,textAlign:"left",display:"flex",alignItems:"center",gap:3,justifyContent:"flex-end"}}>{msg.time}{msg.userId===me.id&&<svg width="18" height="11" viewBox="0 0 18 11" fill="none"><path d="M1 5.5L4.5 9L11 2" stroke={C.success} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"/><path d="M6 5.5L9.5 9L16 2" stroke={C.success} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"/></svg>}</div></div></div>);})}
                  <div ref={msgEnd}/>
                </div>
                <div style={{display:"flex",alignItems:"center",gap:8,padding:"8px 12px",paddingBottom:"calc(8px + env(safe-area-inset-bottom))",borderTop:`1px solid ${C.border}`,background:C.surface,flexShrink:0}}>
                  <label style={{width:42,height:42,borderRadius:"50%",background:C.surfaceAlt,border:"none",cursor:"pointer",color:C.textMuted,display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}>
                    <Icons.Attach/>
                    <input type="file" style={{display:"none"}} onChange={e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{const msg={id:Date.now(),userId:me.id,text:`📎 ${f.name}`,time:nowShamsi(),file:{name:f.name,size:(f.size/1024).toFixed(0)+"KB",data:r.result}};if(dm)setDmMsgs(p=>({...p,[dm]:[...(p[dm]||[]),msg]}));else setMsgs(p=>({...p,[channel]:[...(p[channel]||[]),msg]}));};r.readAsDataURL(f);e.target.value="";}}/>
                  </label>
                  <input style={{flex:1,background:C.surfaceAlt,border:"none",borderRadius:24,padding:"10px 16px",color:C.text,fontSize:16,outline:"none",direction:"rtl",fontFamily:"inherit"}} placeholder="پیام..." value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&sendMsg()}/>
                  <button style={{width:42,height:42,borderRadius:"50%",background:C.teal,border:"none",cursor:"pointer",color:"#fff",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}} onClick={sendMsg}><Icons.Send/></button>
                </div>
              </>
            )}

